### ISSUE TITLE
Cannot define multiple tags without single tag existing

### ISSUE THREAD

**Issue by zaibacu** [CodersOfTheNight/oshino#16]
If config is:
```yaml
tag: something
tags:
  - some tag
  - another tag
```

Everything is OK.
If:
```yaml
tags:
  - some tag
  - another tag
```

Tags array is empty
