### ISSUE TITLE
Noop Mode

### ISSUE THREAD

**Issue by zaibacu** [CodersOfTheNight/oshino#9]
It would be nice to have noop (No Operation) mode

**Comment by zaibacu** [comment]
Note: there's already sort of noop mode (just not as clear as we would want)
```yaml
riemann:
  host: localhost
  port: 5555
  transport: BlankTransport
```

`BlankTransport` is intended for `riemann-client` testing purposes and it does not send any events, which is perfect for noop mode. We need to make usage more convenient
